"""add guest_name to tournament_participant

Revision ID: 5b08795a9c46
Revises: eae269a8ba00
Create Date: 2025-05-09 20:36:57.217367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b08795a9c46'
down_revision = 'eae269a8ba00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=128), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('unique_tournament_participant', type_='unique')
        batch_op.create_unique_constraint('unique_tournament_participant', ['tournament_id', 'user_id', 'guest_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_participant', schema=None) as batch_op:
        batch_op.drop_constraint('unique_tournament_participant', type_='unique')
        batch_op.create_unique_constraint('unique_tournament_participant', ['tournament_id', 'user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
